import { InvokeOptions, ScriptEventListener, SendOptions, SerializableValue } from "./common.js";
/**
 * An IPC router. This must be constructed to send and recieve IPC events.
 */
export declare class Router {
    /**
     * A **unique** ID for this router. If another router has the same ID, it may cause problems.
     * Must be less characters than {@link MAX_ROUTER_UID_LENGTH}.
     */
    readonly uid: string;
    private internalIsValid;
    /**
     * key = stream ID
     * value = cached content from previous events
     */
    private pendingStreams;
    private listeners;
    /**
     * total number of listener uids generated by this router, used to create unique listener IDs for invoke responses.
     */
    private listenerUidsGenerated;
    /**
     * total number of steam uids generated by this router, used to create unique stream IDs.
     */
    private streamUidsGenerated;
    /**
     * @throws Throws if the UID is invalid.
     */
    constructor(
    /**
     * A **unique** ID for this router. If another router has the same ID, it may cause problems.
     * Must be less characters than {@link MAX_ROUTER_UID_LENGTH}.
     */
    uid: string);
    /**
     * Has this object been destroyed?
     */
    get isValid(): boolean;
    /**
     * Unsubscribe from all Minecraft events and mark this object as invalid.
     */
    destroy(): void;
    /**
     * Registers an IPC listener.
     * @param event The listener ID.
     * @param callback The callback.
     * @throws Throws if another listener is registered with the same ID.
     */
    registerListener(event: string, callback: ScriptEventListener): void;
    /**
     * Removes a listener for an event.
     * @param event The event ID.
     * @returns Returns a boolean indicating whether the listener was removed or not.
     */
    removeListener(event: string): boolean;
    /**
     * Send a one-way IPC event.
     * @throws Throws if the message is too long.
     */
    send(options: SendOptions): void;
    /**
     * Stream a one-way IPC event. The payload has no max length, since it is streamed.
     */
    sendStream(options: SendOptions): Promise<void>;
    /**
     * Send or stream a one-way IPC event. If the payload is greater than the max length then it will be streamed.
     */
    sendAuto(options: SendOptions): Promise<void>;
    /**
     * Send a two-way IPC event.
     * @returns Returns whatever the listener returns.
     * @throws Throws if a response is not recieved within 20 game ticks.
     * @throws Throws if the message is too long.
     */
    invoke(options: InvokeOptions): Promise<SerializableValue>;
    /**
     * Stream a two-way IPC event. The payload has no max length since it is streamed.
     * @returns Returns whatever the listener returns.
     * @throws Throws if a response is not recieved within 20 game ticks (after the entire payload has been streamed).
     * @throws Throws if the message is too long.
     */
    invokeStream(options: InvokeOptions): Promise<SerializableValue>;
    /**
     * Send or stream a two-way IPC event. If the payload is greater than the max length then it will be streamed.
     * @returns Returns whatever the target listener returns.
     * @throws Throws if a response is not recieved within 20 game ticks (after the entire payload has been streamed).
     */
    invokeAuto(options: InvokeOptions): Promise<SerializableValue>;
    private setListener;
    private invokeInternal;
    private invokeStreamInternal;
    private generateListenerUid;
    private generateStreamUid;
    private parseRawPayload;
    private invokeListener;
    private callListener;
    private routeEvent;
    private onScriptEventRecieved;
}
