export default [
    {
        name: ":milk_carton: §eAdmin Menu §r:milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6720109507,
            },
            {
                text: "§c§lModeration",
                subtext: "§iModerate Players & World!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    '/leaf:open @s "adm/moderation_main"',
                ],
                iconID: "rpgiab/entity",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6582286231,
            },
            {
                text: "§2§lWorld Settings",
                subtext: "§iConfigure World Settings!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/world_settings_main",
                ],
                iconID: "rpgiab/world_hand",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6583013681,
            },
            {
                text: "§e§lPlayer Settings",
                subtext: "§iConfigure Player Settings!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/player_settings_main",
                ],
                iconID: "rpgiab/character_edit",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6583128831,
            },
            {
                text: "§l§bChat Settings",
                subtext: "§iConfigure Chat Settings!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/chat_settings_main",
                ],
                iconID: "rpgiab/character_dialogue",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6584142531,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6584295782,
            },
            {
                text: "§l§tAdmin Tools",
                subtext: "§iServer Production Tools!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                id: 6669555121,
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
            },
            {
                text: "§l§nEconomy",
                subtext: "§iConfigure Economy Settings!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/economy_main",
                ],
                iconID: "rpgiab/coins",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6669700571,
            },
            {
                text: "§l§dHolograms",
                subtext: "§iSummon / Edit A Hologram!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/holograms_main",
                ],
                iconID: "rpgiab/anim_frame",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6719483633,
            },
            {
                text: "§l§sMisc Settings",
                subtext: "§iOther Uncategorized Stuff",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/gear",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6719079932,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6719285132,
            },
            {
                text: "§q§lPlugins",
                subtext: "§iConfigure Leafs Plugins!",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/folder_up",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6669886921,
            },
            {
                text: "§e§lCREDITS",
                subtext: "§iContribution!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/credits",
                ],
                iconID: "rpgiab/information",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6718923481,
            },
        ],
        subuis: {},
        scriptevent: "adm/main_menu",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §c§lModeration :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§cWarning's",
                subtext: "§iManage Player's Warning's",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_warnings_main",
                ],
                iconID: "rpgiab/hand_delete",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6584899782,
            },
            {
                text: "§l§6Kick's",
                subtext: "§iManage This Servers Kick's",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    '/leaf:open @s "adm/moderation_kick"',
                ],
                iconID: "rpgiab/entity_delete",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6586205181,
            },
            {
                text: "§l§eMute",
                subtext: "§iManage This Servers Mute's!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:mute",
                ],
                iconID: "rpgiab/party_delete",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6586442781,
            },
            {
                text: "§9§lFreeze",
                subtext: "§iManage This Servers Freeze's",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_freeze_main",
                ],
                iconID: "rpgiab/eye_hide",
                iconOverrides: [],
                requiredTag: "",
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6586897232,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6589774381,
            },
            {
                text: "§l§vBan's",
                subtext: "§iManage This Servers Ban's",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:bans",
                ],
                iconID: "rpgiab/tile_stop",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6587165881,
            },
            {
                text: "§5§lInventory Viewer ",
                subtext: "§cNot Here Yet..",
                action: "/playsound random.glass @s",
                actions: ["/playsound random.glass @s"],
                iconID: "rpgiab/chest",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6589167081,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6591502131,
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §e§lPlayer Settings :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§1Currency Editor",
                subtext: "§iEdit A Players Currency!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:currency_editor",
                ],
                iconID: "rpgiab/coins",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6589318332,
            },
            {
                text: "§5§lEffect Editor",
                subtext: "§iEdit A Players Effects!",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/effects_editor",
                ],
                iconID: "vanilla_items/potion_bottle_lingering_regeneration",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6589389632,
            },
            {
                text: "§l§2Nametag Editor",
                subtext: "§iEdit A Players Nametag!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:nametags_plus_config",
                ],
                iconID: "vanilla_items/name_tag",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6589537782,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6591188934,
            },
        ],
        subuis: {},
        scriptevent: "adm/player_settings_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§bChat Settings :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§c§lClear Chat",
                subtext: "§iClears All Recent Chats!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    '/leaf:tell_formatted @a "§0                                                                        \n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n§cChat Has Been Cleared By: §a<name>"',
                ],
                iconID: "rpgiab/dialogue",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6590231231,
            },
            {
                text: "§e§lChat Mute",
                subtext: "§iMutes All Player's",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/clear",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6590349383,
            },
            {
                text: "§b§lRoles",
                subtext: "§iEdit Servers Roles!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/roles_main",
                ],
                iconID: "rpgiab/font_size",
                iconOverrides: [],
                requiredTag: "",
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6715240081,
            },
            {
                text: "§l§9Chat Format",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:chatformat_config",
                ],
                iconID: "rpgiab/expression",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6716740981,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6591401884,
            },
        ],
        subuis: {},
        scriptevent: "adm/chat_settings_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §c§lWarning's :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§a§lAdd Warning",
                subtext: "§iAdd Warnings To Player's!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_warnings_add",
                ],
                iconID: "rpgiab/add",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6608531449,
            },
            {
                text: "§c§lRemove Warning's",
                subtext: "§iRemove Player's Warnings",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_warnings_remove",
                ],
                iconID: "rpgiab/clear",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6608633399,
            },
            {
                text: "§l§1View Warnings",
                subtext: "§iView Player's Warnings",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_warnings_view",
                ],
                iconID: "rpgiab/eye",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6608761448,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsount note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/moderation_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6608827448,
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_warnings_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §a§lAdd Warning :milk_carton:",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§i<name>",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scoreboard players add <name> warnings 1",
                    '/leaf:tell_formatted @a "§8§l[§cMODERATION§8] - §r<name> §8Has Recieved A Warning!"',
                ],
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6609187298,
                meta: "#PLAYER_LIST",
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_warnings_add",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §c§lRemove Warning's :milk_carton:",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§i<name>",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scoreboard players remove <name>[scores={warnings=1..}] warnings 1",
                ],
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6609658953,
                meta: "#PLAYER_LIST",
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_warnings_remove",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §1§lView Warnings :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [],
        subuis: {},
        scriptevent: "adm/moderation_warnings_view",
        cancel: "/playsound random.glass @s",
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§6Kick's :milk_carton:",
        scriptevent: "adm/kick_reason",
        type: 3,
        controls: [
            {
                id: 1748520808627,
                type: "text-field-using-command",
                label: "Reason",
                placeholder: "Type a reason here...",
                preserve: false,
                action: '/kick "<$1>" <value>',
            },
        ],
        submitText: "Kick",
        afterSubmitAction: '/leaf:open @s "adm/moderation_main"',
        folder: 1748493813421897,
    },
    {
        name: "Kick",
        body: "",
        layout: 5,
        type: 0,
        buttons: [
            {
                text: "<name>",
                subtext: "",
                action: '/leaf:open @s "adm/kick_reason"',
                actions: ['/leaf:open @s "adm/kick_reason [<name>]"'],
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6611433888,
                meta: "#PLAYER_LIST",
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_kick",
        cancel: "",
        folder: 1748493813421897,
    },
    {
        name: "§9§lFreeze",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§3§lAdd Freeze",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_freeze_add",
                ],
                iconID: "rpgiab/eye_hide",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6612353398,
            },
            {
                text: "§c§lRemove Freeze",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/moderation_freeze_remove",
                ],
                iconID: "rpgiab/clear",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6612401799,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/moderation_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6612444398,
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_freeze_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: "§s§lAdd Freeze",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§i<name>",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/effect <name> blindness 9999 255 true",
                    "/title <name> actionbar §c§lFROZEN",
                    '/leaf:tell_formatted @a "§8§l[§cMODERATION§8] - §r<name> §8Has Been Froze By §r<name2>"',
                    "/inputpermission set <name> movement disabled",
                    "/inputpermission set <name> camera disabled",
                    "/gamemode a <name>",
                ],
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6612753848,
                meta: "#PLAYER_LIST",
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_freeze_add",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: "§l§cRemove Freeze",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§i<name>",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/effect <name> clear",
                    "/title <name> actionbar §a§lUN-FROZEN",
                    '/leaf:tell_formatted @a "§8§l[§cMODERATION§8] - §r<name> §8Has Been Un-Froze By §r<name2>"',
                    "/inputpermission set <name> movement enabled",
                    "/inputpermission set <name> camera enabled",
                    "/playsound note.chime <name>",
                    "/gamemode s <name>",
                ],
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6613983849,
                meta: "#PLAYER_LIST",
            },
        ],
        subuis: {},
        scriptevent: "adm/moderation_freeze_remove",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: "§l§cCombat Settings",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§iC-Log - :red_dot:",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/tag @s add clog_disable",
                    "/scriptevent leaf:set_bool_property CLog true",
                    "/scriptevent leaf:open adm/world_settings_cb",
                ],
                iconID: "rpgiab/delete",
                iconOverrides: [],
                requiredTag: "!$cfg/CLog",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748527845224,
            },
            {
                text: "§iC-Log - :green_dot:",
                subtext: "",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:set_bool_property CLog false",
                    "/scriptevent leaf:open adm/world_settings_cb",
                ],
                iconID: "rpgiab/checkmark",
                iconOverrides: [],
                requiredTag: "$cfg/CLog",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6616652934,
                conditionalActions: true,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/world_settings_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6709350986,
            },
        ],
        subuis: {},
        scriptevent: "adm/world_settings_cb",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §s§lMob Settings :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§c§lClear Mobs",
                subtext: "§iClears All Mobs Spawned!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/kill @e[family=monster]",
                ],
                iconID: "rpgiab/bomb",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6670208623,
            },
            {
                text: "more coming soon idk",
                subtext: "what to rlly put in here",
                action: "/playsound random.glass @s",
                actions: ["/playsound random.glass @s"],
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6670282821,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/world_settings_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6709214236,
            },
        ],
        subuis: {},
        scriptevent: "adm/mob_settings_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §6§lWeather Editor :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§i§lClear Weather",
                subtext: "Clears All Weather.",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/blip_orange",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6708764486,
            },
            {
                text: "§i§lDownpour",
                subtext: ":green_dot:",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/checkmark",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 1748618214576,
            },
            {
                text: "§i§lDownpour",
                subtext: ":red_dot:",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/checkmark",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 1748618191575,
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/world_settings_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6670999771,
            },
        ],
        subuis: {},
        scriptevent: "adm/weather_settings_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §1§lCurrency Editor :milk_carton:",
        body: "cant figure it out",
        layout: 4,
        type: 0,
        buttons: [],
        subuis: {},
        scriptevent: "adm/currency_editor",
        cancel: "/playsound random.glass @s",
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §d§lEffect Editor :milk_carton:",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/player_settings_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6710758137,
            },
            {
                text: "§a§lNight Vision",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "vanilla_items/potion_bottle_nightVision",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6710856537,
            },
            {
                text: "§l§bSpeed ",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "vanilla_items/potion_bottle_moveSpeed",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6710921188,
            },
            {
                text: "§6§lFire Resistance",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "vanilla_items/potion_bottle_healthBoost",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6711525885,
            },
            {
                text: "§5§lResistance",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "vanilla_items/potion_bottle_confusion",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6711644585,
            },
            {
                text: "§c§lProtection",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "vanilla_items/potion_bottle_digSlowdown",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6711727786,
            },
        ],
        subuis: {},
        scriptevent: "adm/effect_editor",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §2§lNametag Editor :milk_carton:",
        body: "§eSelect A Player.",
        layout: 4,
        type: 0,
        buttons: [],
        subuis: {},
        scriptevent: "adm/nametag_editor",
        cancel: "/playsound random.glass @s",
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §t§lAdmin Tools :milk_carton:",
        body: "§eSelect A Tool.",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§lStructure Void",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s structure_void",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6712708887,
            },
            {
                text: "§lStructure Block",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s structure_block",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622196725,
            },
            {
                text: "§lCommand Block",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s command_block",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622170125,
            },
            {
                text: "§lBarrier",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s barrier",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622220626,
            },
            {
                text: "§lBorder Block",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s border_block",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622758275,
                disabled: false,
            },
            {
                text: "§lDeny",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s deny",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622255826,
                disabled: false,
            },
            {
                text: "§lAllow",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s allow",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622284026,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6712906387,
            },
            {
                text: "§l§bBeing Editor",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s leaf:entity_editor",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622308226,
                disabled: false,
            },
            {
                text: "§l§2Block Editor",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s leaf:block_editor",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622437676,
                disabled: false,
            },
            {
                text: "§l§5Block Dev Tool",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s leaf:block_devtool",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748622964225,
                disabled: false,
            },
            {
                text: "§l§5Being Dev Tool",
                subtext: "§i[Click To Receive]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/admin_tools",
                    "/give @s leaf:entity_devtool",
                ],
                iconID: "rpgiab/tools",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 1748623084276,
                disabled: false,
            },
            {
                text: "§4§lBACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6713086787,
            },
        ],
        subuis: {},
        scriptevent: "adm/admin_tools",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§nEconomy :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§eServer Shop",
                subtext: "§iEdit The Servers Shop!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:shop_admin",
                ],
                iconID: "rpgiab/ui_toolbar",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6714120387,
            },
            {
                text: "§l§5Server Currency",
                subtext: "§iEdit The Servers Currency!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:currency_editor",
                ],
                iconID: "rpgiab/coins",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6714365487,
            },
            {
                text: "§l§sPlayer Shops",
                subtext: "§iEdit Players Shops!",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:player_shop_root",
                ],
                iconID: "rpgiab/entity",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6717546630,
            },
            {
                text: "§6§lAuction House",
                subtext: "§iEdit Servers Auction House",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:ah_root",
                ],
                iconID: "rpgiab/mesh_preview",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6717871931,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6713856137,
            },
        ],
        subuis: {},
        scriptevent: "adm/economy_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§bRoles :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§aAdd Role",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:add_rank",
                ],
                iconID: "rpgiab/expand",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6715395184,
            },
            {
                text: "§e§lEdit Roles",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leafgui:ranks_edit",
                ],
                iconID: "rpgiab/pencil",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6716007330,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/chat_settings_main",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6716066881,
            },
        ],
        subuis: {},
        scriptevent: "adm/roles_main",
        cancel: "/playsound random.glass @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§dHolograms :milk_carton:",
        body: "",
        layout: 4,
        type: 0,
        buttons: [
            {
                text: "§l§aAdd Floating Text",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/floating_text",
                ],
                iconID: "rpgiab/expand",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 1748629154871,
            },
            {
                text: "§l§eRemove Floating Text",
                subtext: "§cNot Here Yet..",
                action: "/playsound note.bell @s",
                actions: ["/playsound note.bell @s"],
                iconID: "rpgiab/scissors",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6719715482,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6719727032,
            },
            {
                text: "§l§aAdd Leaderboard",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/leaderboard",
                ],
                iconID: "rpgiab/expand",
                iconOverrides: [],
                requiredTag: "",
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                disabled: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
                id: 6719649482,
            },
            {
                text: "§l§eRemove Leaderboard",
                subtext: "§i[Click To Open]",
                action: "/playsound note.bell @s",
                actions: [
                    "/playsound note.bell @s",
                    "/scriptevent leaf:open adm/leaderboard_remove",
                ],
                iconID: "rpgiab/scissors",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 1748629183071,
                displayOverrides: [],
                sellButtonEnabled: false,
                buyButtonEnabled: false,
                nutUIHalf: 0,
                nutUINoSizeKey: false,
                nutUIAlt: false,
                nutUIColorCondition: "",
                nutUIHeaderButton: false,
            },
            {
                text: " ",
                subtext: null,
                action: "",
                actions: [""],
                iconID: "",
                iconOverrides: [],
                requiredTag: "",
                type: "divider",
                id: 6719796358,
            },
            {
                text: "§l§4BACK",
                subtext: "",
                action: "/playsound note.chime @s",
                actions: [
                    "/playsound note.chime @s",
                    "/scriptevent leaf:open adm/main_menu",
                ],
                iconID: "rpgiab/variable_return",
                iconOverrides: [],
                requiredTag: "",
                disabled: false,
                id: 6719834556,
            },
        ],
        subuis: {},
        scriptevent: "adm/holograms_main",
        cancel: "/playsound note.bell @s",
        theme: 25,
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§dFloating Text :milk_carton:",
        scriptevent: "adm/floating_text",
        type: 3,
        controls: [
            {
                id: 1748630213670,
                type: "text-field-using-command",
                label: "Example:",
                placeholder: "hey its me frog :3",
                preserve: false,
                action: "/execute as @s at @s run /scriptevent leaf:speak_as !floating-text <value>",
            },
        ],
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§dLeaderboard :milk_carton:",
        scriptevent: "adm/leaderboard",
        type: 3,
        controls: [
            {
                id: 1748630553471,
                type: "text-field-using-command",
                label: "Example:",
                placeholder: "money",
                preserve: false,
                action: "/execute as @s at @s run /scriptevent leaf:speak_as !lb add <value>",
            },
        ],
        submitText: "",
        afterSubmitAction: "",
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§cRemove §dLeaderboard :milk_carton:",
        scriptevent: "adm:leaderboard_remove",
        type: 3,
        controls: [
            {
                id: 1748631021971,
                type: "text-field-using-command",
                label: "Example:",
                placeholder: "money",
                preserve: false,
                action: "/execute as @s at @s run /scriptevent leaf:speak_as !lb remove <value>",
            },
        ],
        folder: 1748493813421897,
    },
    {
        name: ":milk_carton: §l§eCREDITS :milk_carton:",
        scriptevent: "adm/credits",
        type: 3,
        controls: [
            { id: 1748631586071, type: "header", text: "§a§lFroggy :3" },
            { id: 1748631491171, type: "divider" },
            {
                id: 1748631534821,
                type: "label",
                text: "Hello, Im froggy and i made the whole admin ui :3 (cuz im like that) §a(i make free uis hehe)",
            },
        ],
        folder: 1748493813421897,
    },
];
