export default {
    perms: [
        ["Code Block", "codeblock"],
        ["Permissions Testing", "permissions.testing"],
        ["Open Config UI", "config.open"],
        ["Edit Leaderboards", "config.leaderborads"],
        ["Configure Clans", "config.clans"],
        ["Configure Auction House", "config.auctionhouse"],
        ["Configure Custom Nametags", "config.nametags"],
        ["Configure Random Teleport", "config.rtp"],
        ["Edit Snippet Book UI", "config.snippetbook"],
        ["Edit Roles", "config.roleeditor"],
        ["Configure Mines", "config.mineconfig"],
        ["Configure Player Settings", "config.playersettings"],
        ["Configure Platform Settings", "config.platformsettings"],
        ["Configure Gift Codes", "config.gifts"],
        ["Use Preset Browser", "config.presetbrowser"],
        ["Toggle Leaf Features", "config.features&experiments"],
        ["Use Customizer", "config.customizer"],
        ["Full Customizer Access", "config.customizer.full"],
        ["Delete Customizer Creations", "config.customizer.delete"],
        ["Edit Economy", "config.economy.edit"],
        ["Enable Moderation Features", "config.moderationhub"],
        ["Edit Zones", "config.zones"],
        ["Edit Land Claims", "config.landclaims"],
        ["Bypass Zones", "zone.bypass"],
        ["Bypass Land Claims", "claim.bypass"],
        ["Bypass Generator Owner Requirements", "generator.manage"],
        ["View undeployed copies in action forms by default", "uibuilder.actionform.viewundeployedcopies"],
        ["Anticheat Logs", "anticheat.logs"]
    ],
    defaultPermissions: [
        "permissions.testing",
        "commands.pwarp",
        "commands.pwarp.set",
        "commands.pwarp.tp",
        "commands.rtp",
        "commands.what",
        "commands.msg",
        "commands.help",
        "commands.help.version",
        "commands.help.my-id",
        "commands.tpa",
        "commands.warp",
        "commands.report",
        "commands.emojis",
        "commands.pay",
        "commands.redeem",
        "commands.ah",
        "commands.clan",
        "commands.spawn"
    ]
}