import uiBuilder from "./api/uiBuilder";
// console.warn("?");
uiBuilder.addInternalUI({
    name: "Clan Members",
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Go back",
            action: "/scriptevent leaf:open leaf/clans",
            actions: ["/scriptevent leaf:open leaf/clans"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8140536342,
        },
        {
            text: '{{clan_owner "§v" "§b"}}<name>',
            subtext: '{{clan_owner "Owner" "Member"}}',
            action: "/scriptevent leaf:open leaf/clan-members/manage [<name>] [<id>]",
            actions: [
                '{{clan_owner "/scriptevent leaf:open leaf/clan-members" "/scriptevent leaf:open leaf/clan-members/manage [<name>] [<id>]"}}',
            ],
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8140169318,
            meta: "#CLAN_MEMBERS",
            iconID: "rpgiab/character",
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
    ],
    subuis: {},
    scriptevent: "leaf/clan-members",
    cancel: "",
    theme: 25,
    folder: 1750056179413729,
});
uiBuilder.addInternalUI({
    name: "Create a Clan",
    scriptevent: "leaf/create-clan",
    type: 3,
    controls: [
        {
            id: 1750043809039,
            type: "text-field-using-command",
            label: "Clan Name",
            placeholder: "Type a name for your clan here.",
            preserve: true,
            action: '/scriptevent ocapi:create_clan {"name":"<valueSafe>","success":"scriptevent leaf:open leaf/clans","failure":"scriptevent leaf:open leaf/create-clan"}',
        },
    ],
    submitText: "",
    afterSubmitAction: "",
    folder: 1750056179413729,
});

uiBuilder.addInternalUI({
    name: "Clan Invites",
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Go back",
            action: "/scriptevent leaf:open leaf/clans",
            actions: ["/scriptevent leaf:open leaf/clans"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8136362815,
        },
        {
            text: "§b<clan2>",
            subtext: "From <name2>",
            action: "/",
            actions: ["/"],
            iconID: "^textures/azalea_icons/incoming_req",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8136441516,
            meta: "#INVITES ClanInvite",
        },
        {
            text: "§cInvite to <name>",
            subtext: "Outgoing",
            action: "/",
            actions: ["/"],
            iconID: "^textures/azalea_icons/outgoing_req",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 1750045921556,
            meta: "#INVITES ClanInvite out",
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
    ],
    subuis: {},
    scriptevent: "leaf/clan-invites",
    cancel: "",
    theme: 25,
    folder: 1750056179413729,
});

uiBuilder.addInternalUI({
    name: 'Manage "<$1>"',
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Go Back",
            action: "/scriptevent leaf:open leaf/clan-members",
            actions: ["/scriptevent leaf:open leaf/clan-members"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8140623903,
        },
        {
            text: "§eTransfer Ownership",
            subtext: "Transfer ownership of this clan",
            action: '/scriptevent leafgui:confirmation "Are you sure you want to transfer ownership to §v<$1>§r?" "/scriptevent ocapi:transfer_ownership <$2>" "/scriptevent leaf:open leaf/clan-members/manage [<$1>] [<$2>]"',
            actions: [
                '/scriptevent leafgui:confirmation "Are you sure you want to transfer ownership to §v<$1>§r?" "/scriptevent ocapi:transfer_ownership <$2>" "/scriptevent leaf:open leaf/clan-members/manage [<$1>] [<$2>]"',
            ],
            iconID: "rpgiab/character_item_get",
            iconOverrides: [],
            requiredTag: "$CLAN_OWNER",
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            disabled: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
            id: 8140677599,
        },
        {
            text: "§cKick",
            subtext: "Kick this user",
            action: "/",
            actions: [
                '/scriptevent leafgui:confirmation "Are you sure you want to kick §v<$1>§r?" "/scriptevent ocapi:kick <$2>" "/scriptevent leaf:open leaf/clan-members/manage [<$1>] [<$2>]"',
            ],
            iconID: "rpgiab/bomb",
            iconOverrides: [],
            requiredTag: "$CLAN_OWNER",
            disabled: false,
            id: 8140825203,
        },
    ],
    subuis: {},
    scriptevent: "leaf/clan-members/manage",
    cancel: "",
    theme: 25,
    folder: 1750056179413729,
});

uiBuilder.addInternalUI({
    name: "Clan Options",
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Go Back",
            action: "/scriptevent leaf:open leaf/clans",
            actions: ["/scriptevent leaf:open leaf/clans"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8145648849,
        },
        {
            text: "§aToggle Public",
            subtext: "This clan is currently public :green_dot:",
            action: "/scriptevent ocapi:make_private",
            actions: [
                "/scriptevent ocapi:make_private",
                "/scriptevent leaf:open leaf/clan-options",
            ],
            iconID: "rpgiab/world",
            iconOverrides: [],
            requiredTag: "$PUBLIC_CLAN",
            disabled: false,
            id: 8145736399,
        },
        {
            text: "§cToggle Public",
            subtext: "This clan is currently private :red_dot:",
            action: "/scriptevent ocapi:make_private",
            actions: [
                "/scriptevent ocapi:make_public",
                "/scriptevent leaf:open leaf/clan-options",
            ],
            iconID: "rpgiab/world",
            iconOverrides: [],
            requiredTag: "!$PUBLIC_CLAN",
            disabled: false,
            id: 1750055184849,
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
        {
            text: "§eSet application questions",
            subtext: "Set clan questions",
            action: "/scriptevent leaf:open leaf/clan-set-questions",
            actions: ["/scriptevent leaf:open leaf/clan-set-questions"],
            iconID: "rpgiab/missing",
            iconOverrides: [],
            requiredTag: "$CLAN_OWNER && $PUBLIC_CLAN",
            disabled: false,
            id: 8151119057,
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
    ],
    subuis: {},
    scriptevent: "leaf/clan-options",
    cancel: "",
    theme: 25,
    folder: 1750056179413729,
    internal: true,
    internalID: 10,
});
uiBuilder.addInternalUI({
    name: "Set Clan Questions",
    scriptevent: "leaf/clan-set-questions",
    type: 3,
    controls: [
        {
            id: 1750060771122,
            type: "text-field-using-command",
            label: "Clan Questions (comma separated)",
            placeholder: "Question 1, Question 2",
            preserve: true,
            action: '/scriptevent ocapi:set_questions {"questions":"<valueSafe>","after":"/scriptevent leaf:open leaf/clan-options"}',
        },
    ],
});
uiBuilder.addInternalUI({
    name: "Clan Applications",
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Click to Go Back",
            action: "/scriptevent leaf:open leaf/clans",
            actions: ["/scriptevent leaf:open leaf/clans"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8152690079,
        },
        {
            text: "§bApplication from <from>",
            subtext: "[ Click to View ]",
            action: "/",
            actions: ["/"],
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8152509939,
            meta: "#CLAN_APPLICATIONS",
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
    ],
    subuis: {},
    scriptevent: "leaf/clan-applications",
    cancel: "",
    theme: 25,
});
uiBuilder.addInternalUI({
    name: "Public Clans",
    body: "",
    layout: 4,
    type: 0,
    buttons: [
        {
            text: "§6Back",
            subtext: "Go Back",
            action: "scriptevent leaf:open leaf/clans",
            actions: ["scriptevent leaf:open leaf/clans"],
            iconID: "rpgiab/door",
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8145965460,
        },
        {
            text: "§b<clan_name>",
            subtext: "Owner: <clan_owner>",
            action: '/scriptevent leafgui:confirmation "Are you sure you want to join <clan_name>§r?" "/scriptevent ocapi:join_clan <clan_id>" "/scriptevent leaf:open leaf/public-clans"',
            actions: [
                '/scriptevent leafgui:confirmation "Are you sure you want to join <clan_name>§r?" "/scriptevent ocapi:join_clan2 <clan_id>" "/scriptevent leaf:open leaf/public-clans"',
            ],
            iconOverrides: [],
            requiredTag: "",
            disabled: false,
            id: 8146273357,
            meta: "#PUBLIC_CLANS",
            displayOverrides: [],
            sellButtonEnabled: false,
            buyButtonEnabled: false,
            nutUIHalf: 0,
            nutUINoSizeKey: false,
            nutUIAlt: false,
            nutUIColorCondition: "",
            nutUIHeaderButton: false,
        },
    ],
    subuis: {},
    scriptevent: "leaf/public-clans",
    cancel: "",
    folder: 1750056179413729,
    internal: true,
    internalID: 10,
    theme: 25,
});
uiBuilder.addInternalUI({
  "name": "Clans",
  "body": "",
  "layout": 4,
  "type": 0,
  "buttons": [
    {
      "text": "§bCreate Clan",
      "subtext": "Create a clan!",
      "action": "/scriptevent leaf:open leaf/create-clan",
      "actions": [
        "/scriptevent leaf:open leaf/create-clan"
      ],
      "iconID": "rpgiab/add",
      "iconOverrides": [],
      "requiredTag": "!$cfg/clans:enable_pay_to_create && !$IN_CLAN",
      "disabled": false,
      "id": 8134283408,
      "displayOverrides": [],
      "altBtnColorOverride": -1,
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§bCreate Clan",
      "subtext": "{{currency \"{{getProperty \"clans:clan_price_currency\"}}\" \"I\"}} {{getProperty \"clans:clan_price\"}}",
      "action": "/scriptevent leaf:open leaf/create-clan",
      "actions": [
        {
          "type": 1,
          "label": "not enough money",
          "condition": "<vleaf:cc $N/clans:clan_price",
          "stopExec": false,
          "waitTime": 0,
          "waitFormat": "",
          "actions": [
            {
              "type": 0,
              "action": "/leaf:tell_formatted @s \"§cYou do not have enough money to create a clan!\""
            },
            {
              "type": 0,
              "action": "/playsound random.glass @s"
            },
            {
              "type": 0,
              "action": "/scriptevent leaf:open leaf/clans"
            }
          ]
        },
        {
          "type": 1,
          "label": "enough",
          "condition": ">=vleaf:cc $N/clans:clan_price",
          "stopExec": false,
          "waitTime": 0,
          "waitFormat": "",
          "actions": [
            {
              "type": 0,
              "action": "/scriptevent leafgui:confirmation \"Are you sure you want to spend {{currency \"{{getProperty \"clans:clan_price_currency\"}}\"}} to buy a clan?\" \"/scriptevent leaf:add_money {{getProperty \"clans:clan_price_currency\"}} -{{getProperty \"clans:clan_price\"}}\\\\+/scriptevent leaf:open leaf/create-clan\" \"/scriptevent leaf:open leaf/clans\""
            }
          ]
        }
      ],
      "iconID": "rpgiab/add",
      "iconOverrides": [],
      "requiredTag": "!$IN_CLAN && $cfg/clans:enable_pay_to_create",
      "disabled": false,
      "id": 1766981336297,
      "displayOverrides": [],
      "altBtnColorOverride": -1,
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§aInvites",
      "subtext": "View your invites to clans",
      "action": "/scriptevent leaf:open leaf/clan-invites",
      "actions": [
        "/scriptevent leaf:open leaf/clan-invites"
      ],
      "iconID": "rpgiab/anvil_in",
      "iconOverrides": [],
      "requiredTag": "!$IN_CLAN",
      "disabled": false,
      "id": 8136318017,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§aPublic §bClans",
      "subtext": "Browse public clans",
      "action": "/scriptevent leaf:open leaf/public-clans",
      "actions": [
        "/scriptevent leaf:open leaf/public-clans"
      ],
      "iconID": "rpgiab/world",
      "iconOverrides": [],
      "requiredTag": "!$IN_CLAN",
      "disabled": false,
      "id": 8146394962
    },
    {
      "text": "§eSet Clan Base",
      "subtext": "Set this clans base",
      "action": "/scriptevent ocapi:set_base",
      "actions": [
        "/scriptevent ocapi:set_base",
        "/playsound note.pling",
        "/leaf:open @s \"leaf/clans\""
      ],
      "iconID": "rpgiab/main_menu",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER && $cfg/clans:enable_clan_base",
      "disabled": false,
      "id": 8135143555
    },
    {
      "text": "§cRemove Clan Base",
      "subtext": "Remove this clans base",
      "action": "/scriptevent ocapi:set_base",
      "actions": [
        "/scriptevent ocapi:remove_base",
        "/playsound note.pling",
        "/leaf:open @s \"leaf/clans\""
      ],
      "iconID": "rpgiab/main_menu",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER && $HAS_CLAN_BASE && $cfg/clans:enable_clan_base",
      "disabled": false,
      "id": 1750044899550,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§dGo to Clan Base",
      "subtext": "Teleport to this clans base",
      "action": "/playsound mob.endermen.portal",
      "actions": [
        "/playsound mob.endermen.portal",
        "/scriptevent ocapi:teleport_to_clan_base"
      ],
      "iconID": "rpgiab/main_menu",
      "iconOverrides": [],
      "requiredTag": "$HAS_CLAN_BASE && $cfg/clans:enable_clan_base",
      "disabled": false,
      "id": 1750044568251,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§aClan Chat",
      "subtext": "Currently in clan chat :green_dot:",
      "action": "tag @s remove clan-chat",
      "actions": [
        "tag @s remove clan-chat",
        "/leaf:open @s \"leaf/clans\""
      ],
      "iconID": "rpgiab/dialogue",
      "iconOverrides": [],
      "requiredTag": "clan-chat && $IN_CLAN",
      "disabled": false,
      "id": 8135650635,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§cClan Chat",
      "subtext": "Currently in global chat :red_dot:",
      "action": "tag @s add clan-chat",
      "actions": [
        "tag @s add clan-chat",
        "/leaf:open @s \"leaf/clans\""
      ],
      "iconID": "rpgiab/dialogue",
      "iconOverrides": [],
      "requiredTag": "!clan-chat && $IN_CLAN",
      "disabled": false,
      "id": 1750045074962,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§bSend Invite",
      "subtext": "Send a clan invite to someone!",
      "action": "/scriptevent leafgui:invites ClanInvites \"/scriptevent leaf:open leaf/clans\"",
      "actions": [
        "/scriptevent leafgui:invite ClanInvite \"/scriptevent leaf:open leaf/clans\""
      ],
      "iconID": "rpgiab/dialogue_start",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER",
      "disabled": false,
      "id": 8136223424
    },
    {
      "text": "§eClan Members",
      "subtext": "Manage members in this clan",
      "action": "/scriptevent leaf:open leaf/clan-members",
      "actions": [
        "/scriptevent leaf:open leaf/clan-members"
      ],
      "iconID": "rpgiab/party",
      "iconOverrides": [],
      "requiredTag": "$IN_CLAN",
      "disabled": false,
      "id": 8139644798,
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false
    },
    {
      "text": "§cDisband",
      "subtext": "Disband this clan",
      "action": "/scriptevent leafgui:confirmation \"Are you sure you want to disband your clan\" \"/scriptevent ocapi:disband\" \"/scriptevent leaf:open leaf/clans\"",
      "actions": [
        "/scriptevent leafgui:confirmation \"Are you sure you want to disband your clan\" \"/scriptevent ocapi:disband\" \"/scriptevent leaf:open leaf/clans\""
      ],
      "iconID": "rpgiab/party_delete",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER",
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "disabled": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false,
      "id": 8139066450
    },
    {
      "text": "§cLeave Clan",
      "subtext": "Leave this clan",
      "action": "/",
      "actions": [
        "/scriptevent leafgui:confirmation \"Are you sure you want to leave this clan?\" \"/scriptevent ocapi:leave\" \"/scriptevent leaf:open leaf/clans\""
      ],
      "iconID": "rpgiab/party_delete",
      "iconOverrides": [],
      "requiredTag": "!$CLAN_OWNER && $IN_CLAN",
      "disabled": false,
      "id": 8139413713
    },
    {
      "text": "§vClan Settings",
      "subtext": "Configure this clan",
      "action": "/scriptevent leaf:open leaf/clan-options",
      "actions": [
        "/scriptevent leaf:open leaf/clan-options"
      ],
      "iconID": "rpgiab/gear",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER",
      "displayOverrides": [],
      "sellButtonEnabled": false,
      "buyButtonEnabled": false,
      "nutUIHalf": 0,
      "nutUINoSizeKey": false,
      "nutUIAlt": false,
      "nutUIColorCondition": "",
      "nutUIHeaderButton": false,
      "id": 8145828706
    },
    {
      "text": "§cApplications",
      "subtext": "View this clans applications",
      "action": "/scriptevent leaf:open leaf/clan-applications",
      "actions": [
        "/scriptevent leaf:open leaf/clan-applications"
      ],
      "iconID": "rpgiab/book",
      "iconOverrides": [],
      "requiredTag": "$CLAN_OWNER && $PUBLIC_CLAN && $CLAN_HAS_QUESTIONS",
      "disabled": false,
      "id": 8152800578
    }
  ],
  "subuis": {},
  "scriptevent": "leaf/clans",
  "cancel": "",
  "theme": 25,
  "folder": 1750056179413729,
  "internal": true,
  "internalID": 11
});
uiBuilder.db.waitLoad().then(() => {
    if (!uiBuilder.db.findFirst({ type: 11, identifier: "ClanInvite" })) {
        uiBuilder.db.insertDocument({
            type: 11,
            identifier: "ClanInvite",
            expirationTime: 1200,
            denyActions: [
                '/leaf:tell_formatted "<name2>" "§cClans §8>> §7<name> denied your invite to your clan"',
                '/leaf:tell_formatted "<name>" "§cClans §8>> §7Denied invite to §b<clan2>"',
            ],
            expireActions: [
                '/leaf:tell_formatted "<name2>" "§cClans §8>> §7Your clan invite to <name> expired"',
                '/leaf:tell_formatted "<name>" "§cClans §8>> §7Your clan invite from <name2> expired"',
            ],
            sendActions: [
                '/leaf:tell_formatted "<name2>" "§cClans §8>> §7Sent clan invite to <name>"',
                '/leaf:tell_formatted "<name>" "§cClans §8>> §7You received an invite from <name2> to join §b<clan2>"',
            ],
            acceptActions: [
                '/leaf:tell_formatted "<name2>" "§cClans §8>> §7<name> joined your clan!"',
                '/leaf:tell_formatted "<name>" "§cClans §8>> §7You are now in §b<clan2>"',
                "/scriptevent ocapi:join_clan <clanID2>",
            ],
            folder: 1750056179413729,
        });
    }
});
